"""SHADOW SIZING LEDGER — offline, observation-only cap-sizing research tool. Reads LIVE Profile A
trade history; never writes an order, never gates or delays one, never touches auto_live/zeus_server/
bridge/config. Same run mode as decay_monitor.py: once per day / manual, fail-open (any internal
error -> one warning line, exit 0).

PURPOSE: for every resolved LIVE Profile A trade, answer "what would each candidate size cap
{15, 20, 25, 30, 40} contracts have sized and earned?" and track a hypothetical eval trajectory per
cap. This is PROMOTION EVIDENCE for a future size-up decision, not a live signal — see the caveat
literally stamped on every emitted row.

DESIGN CONTRACT (fail OPEN, mirrors decay_monitor.py):
  * Pure math (`build_shadow_rows`, `day_rows_for_cap`, `eval_replay`) has no I/O — unit-testable.
  * `run()` wraps every I/O / parsing step so ONE internal error never raises out of this module.
  * Never imports/calls anything in auto_live.py, zeus_server.py, bridge_*.py, or config.

INPUTS (all read-only, existence-guarded):
  1. out/ares/trade_results.csv (trade_results.py) — same ledger decay_monitor.py reads. AUTHORITATIVE
     for resolved $ pnl and the actual live `contracts` filled (== qty_filled here; the ledger's pnl
     was generated by exactly that many contracts, so it IS the ground-truth fill count even before
     any independent broker read-back exists).
  2. logs/live_engine_decisions/<date>.jsonl (ARGUS, decision_log.py) — reused via
     `decay_monitor._read_decision_log_signals` (import, not copy): entry_price/stop_price/qty_total
     per live_send decision. PRIMARY source of entry/stop (matches decay_monitor's own precedence).
  3. out/fill_telemetry/<date>.jsonl (fill_telemetry.py, schema v2) — DECISION rows carry
     qty_formula/qty_cap (decay_monitor's own fill-telemetry reader drops these fields, so this module
     has its own minimal reader); used (a) as the qty_formula source and (b) as a FALLBACK for
     entry/stop when the ARGUS decision log has no match. TOUCH/ORDER_RESOLVED/FILL_CONFIRMED rows
     feed the pooled fill-evidence counters (touch-without-fill, penetration, time-to-fill, partial
     fill) — computed across ALL trades/files every run (cheap, always consistent; no offset needed
     there since it's a pure re-aggregation, same as decay_monitor's rolling stats).

PER RESOLVED LIVE PROFILE-A TRADE, one shadow row per cap C in {15,20,25,30,40}:
  pnl_per_contract = pnl / qty_filled          (qty_filled 0/None -> skip row, reason recorded)
  q_shadow = min(C, qty_formula)               (qty_formula from the matched fill-telemetry DECISION;
                                                 if missing, derived = int(1200 // (|entry-stop| * 2))
                                                 and flagged `derived: true`; if entry/stop are ALSO
                                                 unavailable, the row is skipped, reason recorded)
  shadow_pnl = pnl_per_contract * q_shadow
  every row also carries the literal CAVEAT string (the format enforces the epistemics on purpose).

STORAGE:
  out/shadow_ledger/rows.jsonl   — append-only, one row per (trade, cap).
  out/shadow_ledger/status.json  — per-cap cumulative shadow pnl + a day-level hypothetical eval
                                    trajectory replay (start $50k, target +$3k, EOD trail $2.5k,
                                    lock at start+$100, DLL day-clamp -$1k, internal $550 day stop;
                                    NO intrabar MAE/trough data exists for a shadow trade, so the DLL
                                    clamp is applied to the day's REALIZED total only — a documented
                                    simplification, day-level granularity is fine per spec), plus the
                                    pooled fill-evidence counters kept side-by-side so nobody reads the
                                    shadow P&L without the promotion-relevant evidence next to it.

IDEMPOTENCY: `status["offsets"][ledger_path]` is a high-water mark over RAW trade_results.csv rows
(every row seen, whether it ends up a Profile-A live trade or not) so a daily re-run only turns NEW
ledger rows into new rows.jsonl lines — never double-counted. Decision-log / fill-telemetry files are
small and cheap to fully re-scan every run (matches decay_monitor's own approach); only the ledger
needs a persisted offset because it is the only append-only sink this module itself owns.

Task-3 (break-even matrix) placeholders — reported in status.json, NEVER auto-flagged while None:
  KILL_TOUCH_NO_FILL_PCT = None   # pending vault: Eval Sizing Research note
  KILL_SLIP_R = -0.05

Run mode: `python3 shadow_ledger.py` runs once and exits; `--dry-run` prints instead of writing.
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import os
from collections import defaultdict
from datetime import datetime, timezone

import decay_monitor as DM
import trade_results

CAPS = (15, 20, 25, 30, 40)
RISK_BUDGET_USD = 1200.0
DOLLARS_PER_POINT = trade_results.DOLLARS_PER_POINT

DEFAULT_LEDGER_PATH = trade_results.PATH                        # out/ares/trade_results.csv
DEFAULT_DECISION_LOG_DIR = DM.DEFAULT_DECISION_LOG_DIR           # logs/live_engine_decisions
DEFAULT_FILL_TELEM_DIR = DM.DEFAULT_FILL_TELEM_DIR               # out/fill_telemetry
DEFAULT_ROWS_PATH = "out/shadow_ledger/rows.jsonl"
DEFAULT_STATUS_PATH = "out/shadow_ledger/status.json"

# ---------------------------------------------------------------------------- Task-3 placeholders
KILL_TOUCH_NO_FILL_PCT = None   # set from break-even matrix (vault: Eval Sizing Research note)
KILL_SLIP_R = -0.05

CAVEAT = ("SHADOW FILLS INHERIT THE A10 FILL — upper bound at size; NEVER a promotion criterion alone")

# ---------------------------------------------------------------------------- hypothetical eval spec
EVAL_START = 50_000.0
EVAL_TRAIL = 2_500.0
EVAL_TARGET = 3_000.0
EVAL_LOCK_AT = 100.0            # threshold locks at start+lock_at once peak-trail crosses it
EVAL_DLL = 1_000.0              # day-level DLL clamp (no intrabar trough data for shadow trades)
EVAL_DAY_STOP = 550.0           # internal ARES-style day stop


def _now_iso(now=None):
    return (now or datetime.now(timezone.utc)).isoformat()


# ---------------------------------------------------------------------------- pure sizing math (no I/O)

def shadow_qty(cap, qty_formula):
    """min(cap, uncapped size-to-risk ask), floored at 0."""
    return max(0, min(int(cap), int(qty_formula)))


def _derive_qty_formula(entry, stop, budget=RISK_BUDGET_USD, dpp=DOLLARS_PER_POINT):
    """Fallback size-to-risk formula when the matched DECISION carries no qty_formula:
    int(budget // (|entry-stop| * $/pt)). Returns None if entry==stop (zero risk distance)."""
    try:
        denom = abs(float(entry) - float(stop)) * dpp
    except (TypeError, ValueError):
        return None
    if denom <= 0:
        return None
    return int(budget // denom)


def build_shadow_rows(trade, caps=CAPS):
    """trade: dict with pnl, qty_filled, entry, stop, qty_formula (may be None), ts, date.
    Returns (rows, skip_reason). skip_reason is None on success (rows non-empty), else rows == []."""
    qty_filled = trade.get("qty_filled")
    try:
        qty_filled = int(qty_filled)
    except (TypeError, ValueError):
        return [], "qty_filled_missing_or_zero"
    if qty_filled <= 0:
        return [], "qty_filled_missing_or_zero"

    pnl = trade.get("pnl")
    try:
        pnl = float(pnl)
    except (TypeError, ValueError):
        return [], "pnl_missing"

    entry, stop = trade.get("entry"), trade.get("stop")
    qty_formula = trade.get("qty_formula")
    derived = False
    if qty_formula is None:
        if entry is None or stop is None:
            return [], "no_entry_stop_for_derivation"
        qty_formula = _derive_qty_formula(entry, stop)
        derived = True
        if qty_formula is None:
            return [], "zero_stop_distance"
    try:
        qty_formula = int(qty_formula)
    except (TypeError, ValueError):
        return [], "bad_qty_formula"

    stop_pts = None
    if entry is not None and stop is not None:
        try:
            stop_pts = round(abs(float(entry) - float(stop)), 4)
        except (TypeError, ValueError):
            stop_pts = None

    pnl_per_contract = pnl / qty_filled
    rows = []
    for c in caps:
        q_shadow = shadow_qty(c, qty_formula)
        rows.append({
            "ts": trade.get("ts"),
            "date": trade.get("date"),
            "cap": int(c),
            "q_shadow": q_shadow,
            "q_live": qty_filled,
            "pnl_live": round(pnl, 2),
            "shadow_pnl": round(pnl_per_contract * q_shadow, 2),
            "stop_pts": stop_pts,
            "qty_formula": qty_formula,
            "derived": derived,
            "caveat": CAVEAT,
        })
    return rows, None


# ---------------------------------------------------------------------------- pure trajectory replay (no I/O)

def day_rows_for_cap(rows_for_cap, day_stop=EVAL_DAY_STOP, dll=EVAL_DLL):
    """Collapse one cap's shadow rows to (day, realized) with an internal day-stop applied
    trade-by-trade (chronological, per `ts`/`date`) and a final day-level DLL clamp.

    NO intrabar MAE/trough data exists for a shadow trade (unlike
    tools_account_size_research.day_rows, which has it from the real backtest engine) — the DLL
    clamp here is applied to the day's REALIZED total only, a documented simplification (day-level
    granularity is fine per spec)."""
    days = {}
    for r in sorted(rows_for_cap, key=lambda x: (x.get("date") or "", x.get("ts") or "")):
        d = r.get("date") or (r.get("ts") or "")[:10]
        if not d:
            continue
        day = days.setdefault(d, {"real": 0.0, "stopped": False})
        if day["stopped"]:
            continue
        day["real"] += r.get("shadow_pnl", 0.0)
        if day["real"] <= -day_stop:
            day["stopped"] = True
    out = []
    for d in sorted(days):
        real = days[d]["real"]
        if real <= -dll:
            real = -dll
        out.append((d, real))
    return out


def eval_replay(day_rows, start=EVAL_START, trail=EVAL_TRAIL, target=EVAL_TARGET, lock_at=EVAL_LOCK_AT):
    """Day-level hypothetical eval state machine (EOD ratchet trail, lock at start+lock_at, target
    pass). Conceptually mirrors tools_account_size_research.eval_run at day-level granularity."""
    thr = start - trail
    bal = start
    peak = start
    locked = False
    days_done = 0
    for d, real in day_rows:
        days_done += 1
        bal += real
        peak = max(peak, bal)
        if not locked:
            thr = max(thr, peak - trail)
            if peak - trail >= start + lock_at:
                thr = start + lock_at
                locked = True
        if bal <= thr:
            return {"status": "BUSTED", "days_elapsed": days_done, "balance": round(bal, 2)}
        if bal >= start + target:
            return {"status": "PASSED", "days_elapsed": days_done, "balance": round(bal, 2)}
    return {"status": "RUNNING", "days_elapsed": days_done, "balance": round(bal, 2)}


# ---------------------------------------------------------------------------- source readers (I/O, fail-open per source)

def _read_ledger_raw(path, errors):
    """Every data row of trade_results.csv in file order, UNFILTERED — the offset is counted over
    these raw rows so it stays 1:1 with the persisted high-water mark regardless of which rows later
    get filtered out (paper mode, rejected, non-A strategy, ...)."""
    rows = []
    try:
        if not os.path.exists(path):
            return rows
        with open(path, newline="") as fh:
            rows = list(csv.DictReader(fh))
    except Exception as e:                                      # noqa: BLE001 — one bad source must not sink the run
        errors.append(f"ledger read error ({path}): {e!r}")
    return rows


def _read_ft_decisions(base_dir, errors):
    """fill_telemetry DECISION rows with qty_formula/qty_cap preserved (decay_monitor's own
    fill-telemetry reader drops these schema-v2 sizing-forensics fields, so this is a minimal,
    purpose-built reader rather than a reuse of decay_monitor._read_fill_telemetry_decisions)."""
    rows = []
    if not os.path.isdir(base_dir):
        return rows
    try:
        for fp in sorted(glob.glob(os.path.join(base_dir, "*.jsonl"))):
            try:
                with open(fp) as fh:
                    for ln in fh:
                        ln = ln.strip()
                        if not ln:
                            continue
                        try:
                            r = json.loads(ln)
                        except ValueError:
                            continue
                        if r.get("event") != "DECISION":
                            continue
                        dt = DM._parse_dt(r.get("bar_ts") or r.get("signal_ts") or r.get("ts_utc"))
                        if dt is None:
                            continue
                        entry = r.get("submitted_price") if r.get("submitted_price") is not None else r.get("intended_price")
                        rows.append({
                            "date": dt.date().isoformat(),
                            "dt_et": dt,
                            "account_tag": r.get("account_tag"),
                            "profile": (r.get("strategy") or "A").strip().upper(),
                            "side": (r.get("side") or "").strip().lower(),
                            "entry": entry,
                            "stop": r.get("stop"),
                            "qty_formula": r.get("qty_formula"),
                            "qty_cap": r.get("qty_cap"),
                        })
            except Exception as e:                               # noqa: BLE001
                errors.append(f"fill_telemetry decision read error ({fp}): {e!r}")
    except Exception as e:                                       # noqa: BLE001
        errors.append(f"fill_telemetry decision glob error: {e!r}")
    return rows


def _read_fill_evidence(base_dir, errors):
    """Pooled fill-evidence counters across ALL fill_telemetry files, independent of the resolved-
    trade join — the PROMOTION-relevant numbers (touch-without-fill rate, mean |penetration|, mean
    time-to-fill, partial-fill count). Recomputed fresh every run (cheap; matches decay_monitor's
    own full-rescan-every-run approach for its rolling stats) -- no offset needed here.

    touch-without-fill: an ORDER_RESOLVED row with touch_seq > 0 (the resting order traded through
    at least once but was never confirmed filled -- cancelled/TTL'd/flattened instead)."""
    out = dict(touch_without_fill_count=0, touch_without_fill_rate=None, mean_abs_penetration=None,
               mean_time_to_fill_s=None, partial_fill_count=0, fill_confirmed_count=0,
               distinct_touched_orders=0)
    if not os.path.isdir(base_dir):
        return out

    touch_sids = set()
    touch_without_fill_count = 0
    penetrations = []
    time_to_fills = []
    partial_fill_count = 0
    fill_confirmed_count = 0
    try:
        for fp in sorted(glob.glob(os.path.join(base_dir, "*.jsonl"))):
            try:
                with open(fp) as fh:
                    for ln in fh:
                        ln = ln.strip()
                        if not ln:
                            continue
                        try:
                            r = json.loads(ln)
                        except ValueError:
                            continue
                        ev = r.get("event")
                        if ev == "TOUCH":
                            sid = r.get("sid")
                            if sid is not None:
                                touch_sids.add(sid)
                            lvl, lo, hi, side = r.get("level"), r.get("low"), r.get("high"), r.get("side")
                            if lvl is not None and side in ("long", "short") and lo is not None and hi is not None:
                                try:
                                    pen = (float(lvl) - float(lo)) if side == "long" else (float(hi) - float(lvl))
                                    penetrations.append(abs(pen))
                                except (TypeError, ValueError):
                                    pass
                        elif ev == "ORDER_RESOLVED":
                            ts_seq = r.get("touch_seq")
                            if ts_seq:
                                touch_without_fill_count += 1
                        elif ev == "FILL_CONFIRMED":
                            fill_confirmed_count += 1
                            if r.get("partial_fill"):
                                partial_fill_count += 1
                            ttf = r.get("time_to_fill_s")
                            if ttf is not None:
                                try:
                                    time_to_fills.append(float(ttf))
                                except (TypeError, ValueError):
                                    pass
            except Exception as e:                               # noqa: BLE001
                errors.append(f"fill_telemetry evidence read error ({fp}): {e!r}")
    except Exception as e:                                       # noqa: BLE001
        errors.append(f"fill_telemetry evidence glob error: {e!r}")

    distinct_touched = len(touch_sids)
    rate = (touch_without_fill_count / distinct_touched) if distinct_touched else None
    out.update(
        touch_without_fill_count=touch_without_fill_count,
        touch_without_fill_rate=(round(rate, 4) if rate is not None else None),
        mean_abs_penetration=(round(sum(penetrations) / len(penetrations), 4) if penetrations else None),
        mean_time_to_fill_s=(round(sum(time_to_fills) / len(time_to_fills), 3) if time_to_fills else None),
        partial_fill_count=partial_fill_count,
        fill_confirmed_count=fill_confirmed_count,
        distinct_touched_orders=distinct_touched,
    )
    return out


def _read_rows_file(path, errors):
    rows = []
    try:
        if not os.path.exists(path):
            return rows
        with open(path) as fh:
            for ln in fh:
                ln = ln.strip()
                if not ln:
                    continue
                try:
                    rows.append(json.loads(ln))
                except ValueError:
                    continue
    except Exception as e:                                       # noqa: BLE001
        errors.append(f"rows.jsonl read error ({path}): {e!r}")
    return rows


# ---------------------------------------------------------------------------- join (one raw ledger row -> a trade dict)

def _build_trade(raw_row, dec_by_key, ft_by_key, errors):
    """One raw (unfiltered) ledger CSV row -> a shadow-eligible trade dict, or None if it isn't a
    resolved LIVE Profile-A trade (still counts toward the ledger offset either way -- the offset is
    over raw rows, not eligible ones)."""
    try:
        if (raw_row.get("mode") or "").strip().lower() != "live":
            return None
        if trade_results.is_rejected(raw_row.get("note")):
            return None
        strategy = (raw_row.get("strategy") or "").strip().upper()
        if strategy != "A":
            return None
        try:
            pnl = float(raw_row.get("pnl") or 0)
        except (TypeError, ValueError):
            return None
        date = (raw_row.get("date") or "").strip()
        account = (raw_row.get("account") or "").strip()
        direction = (raw_row.get("direction") or "").strip().lower()
        try:
            qty_filled = int(raw_row.get("contracts"))
        except (TypeError, ValueError):
            qty_filled = None

        key_argus = (date, account, strategy, direction)
        meta_argus = None
        bucket = dec_by_key.get(key_argus)
        if bucket:
            meta_argus = bucket.pop(0)

        meta_ft = None
        tag_fn = DM._account_tag_fn()
        if tag_fn is not None:
            try:
                tag = tag_fn(account)
            except Exception:                                    # noqa: BLE001
                tag = None
            if tag is not None:
                fbucket = ft_by_key.get((date, tag, strategy, direction))
                if fbucket:
                    meta_ft = fbucket.pop(0)

        entry = stop = None
        ts = date
        if meta_argus is not None:
            entry, stop = meta_argus.get("entry"), meta_argus.get("stop")
            ts = meta_argus["dt_et"].isoformat()
        if (entry is None or stop is None) and meta_ft is not None:
            entry = entry if entry is not None else meta_ft.get("entry")
            stop = stop if stop is not None else meta_ft.get("stop")
            if meta_argus is None:
                ts = meta_ft["dt_et"].isoformat()

        qty_formula = meta_ft.get("qty_formula") if meta_ft is not None else None

        return dict(date=date, ts=ts, pnl=pnl, qty_filled=qty_filled, entry=entry, stop=stop,
                    qty_formula=qty_formula)
    except Exception as e:                                       # noqa: BLE001 — one bad row must not sink the run
        errors.append(f"trade-build error: {e!r}")
        return None


# ---------------------------------------------------------------------------- status persistence

def _load_status(status_path):
    try:
        with open(status_path) as fh:
            return json.load(fh)
    except Exception:                                             # noqa: BLE001 — missing/corrupt -> no prior state
        return {}


def _append_rows(rows_path, rows, dry_run):
    if not rows:
        return
    if dry_run:
        for r in rows:
            print(json.dumps(r))
        return
    os.makedirs(os.path.dirname(rows_path) or ".", exist_ok=True)
    with open(rows_path, "a") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


def _write_status(status_path, status, dry_run):
    if dry_run:
        print(json.dumps(status, indent=2))
        return
    try:
        os.makedirs(os.path.dirname(status_path) or ".", exist_ok=True)
        with open(status_path, "w") as fh:
            json.dump(status, fh, indent=2)
    except Exception as e:                                        # noqa: BLE001
        print(f"[shadow_ledger] status write failed (swallowed): {e!r}", flush=True)


# ---------------------------------------------------------------------------- orchestration

def run(*, ledger_path=DEFAULT_LEDGER_PATH, decision_log_dir=DEFAULT_DECISION_LOG_DIR,
        fill_telem_dir=DEFAULT_FILL_TELEM_DIR, rows_path=DEFAULT_ROWS_PATH,
        status_path=DEFAULT_STATUS_PATH, dry_run=False, caps=CAPS, now=None):
    """One fail-open pass. NEVER raises -- any unexpected internal error is caught, logged as a
    single WARNING line, and a minimal status is returned so a cron invocation still exits 0."""
    try:
        errors = []
        prev = _load_status(status_path)
        offset = int((prev.get("offsets") or {}).get(ledger_path, 0))

        raw_rows = _read_ledger_raw(ledger_path, errors)
        new_raw = raw_rows[offset:]

        decision_rows = DM._read_decision_log_signals(decision_log_dir, errors)
        dec_by_key = defaultdict(list)
        for d in decision_rows:
            dec_by_key[(d["date"], d["account"], d["profile"], d["side"])].append(d)

        ft_decisions = _read_ft_decisions(fill_telem_dir, errors)
        ft_by_key = defaultdict(list)
        for f in ft_decisions:
            ft_by_key[(f["date"], f["account_tag"], f["profile"], f["side"])].append(f)

        new_rows = []
        skipped = defaultdict(int)
        n_trades_new = 0
        for raw in new_raw:
            trade = _build_trade(raw, dec_by_key, ft_by_key, errors)
            if trade is None:
                continue
            n_trades_new += 1
            rows, reason = build_shadow_rows(trade, caps=caps)
            if reason:
                skipped[reason] += 1
                continue
            new_rows.extend(rows)

        _append_rows(rows_path, new_rows, dry_run)

        if dry_run:
            all_rows = _read_rows_file(rows_path, errors) + new_rows
        else:
            all_rows = _read_rows_file(rows_path, errors)         # includes just-appended new_rows

        per_cap = {}
        for c in caps:
            rows_c = [r for r in all_rows if r.get("cap") == c]
            cum_pnl = round(sum(r.get("shadow_pnl", 0.0) for r in rows_c), 2)
            drows = day_rows_for_cap(rows_c)
            ev = eval_replay(drows)
            per_cap[str(c)] = dict(cumulative_shadow_pnl=cum_pnl, n_shadow_trades=len(rows_c),
                                    status=ev["status"], days_to_target_so_far=ev["days_elapsed"],
                                    balance=ev["balance"])

        evidence = _read_fill_evidence(fill_telem_dir, errors)

        status = dict(
            ts=_now_iso(now),
            offsets={ledger_path: len(raw_rows)},
            n_trades_new=n_trades_new,
            n_rows_written_this_run=len(new_rows),
            skipped=dict(skipped),
            per_cap=per_cap,
            fill_evidence=evidence,
            kill_touch_no_fill_pct=KILL_TOUCH_NO_FILL_PCT,
            kill_slip_r=KILL_SLIP_R,
            errors=errors,
        )
        _write_status(status_path, status, dry_run)
        return status
    except Exception as e:                                        # noqa: BLE001 — fail OPEN, never raise into a caller
        print(f"[shadow_ledger] WARNING: internal error, shadow sizing skipped this run: {e!r}", flush=True)
        return {"ts": _now_iso(now), "offsets": {}, "n_trades_new": 0, "n_rows_written_this_run": 0,
                "skipped": {}, "per_cap": {}, "fill_evidence": {}, "kill_touch_no_fill_pct": KILL_TOUCH_NO_FILL_PCT,
                "kill_slip_r": KILL_SLIP_R, "errors": [f"fatal: {e!r}"]}


def main(argv=None):
    ap = argparse.ArgumentParser(description="Offline shadow-sizing ledger (observation-only; never gates orders).")
    ap.add_argument("--dry-run", action="store_true", help="print instead of writing")
    a = ap.parse_args(argv)
    run(dry_run=a.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
