"""tools_recert_funded.py — HONEST FUNDED FUNNEL, D1c-lookahead re-certification (INC-20260706-1141).

HONEST-RECERT DRAFT — pending auditor verdict + operator approval.

RESEARCH/REPORTING HARNESS ONLY. Does not modify `apex_funded_40.py` (read-only import of its
lifecycle constants + its own certified `run_pa`) and does not touch any live/config/funded-config
file. LIVE HOLD ACTIVE.

Why a new file instead of editing `apex_funded_40.py`: that module's `daily_series(rows, a_size,
budget_per_ct=160.0)` ties the per-trade $ budget to the contract cap via a single ratio
(budget = 160 * a_size). This task's sizing grid needs INDEPENDENT (budget $, cap contracts) pairs
that do not follow that ratio (e.g. 480/A5, not just 160*a_size). `daily_series` below is a
generalization of `apex_funded_40.daily_series` to (budget, cap) — same clamp/stop logic,
reproduced verbatim (verified by the CANARY in `main()` before anything else runs). `run_pa`
itself is NOT reimplemented: it is imported and called unmodified from `apex_funded_40` (it only
consumes the (day, real, trough) list — it has no sizing-shaped inputs to generalize). A separate
`run_pa_instrumented` (same rules, extra bookkeeping only) is used for the funnel breakdown
(safety-net reach, payout list, start-year), verified against `apex_funded_40.run_pa` in the same
canary.

Stream: HONEST D1c (post-fix, INC-20260706-1141), loaded via
`tools_sim_parity_check.load_rows()` exactly as instructed — NOT regenerated by any other path.

Apex 4.0 EOD 50K rules (unchanged from `apex_funded_40.py`, imported not retyped): START $50,000,
TRAIL $2,500, LOCK_EOD $52,600 (locks threshold at start+$100), DLL -$1,000 (day-clamp),
DAILY_STOP -$550, MIN_REQ $52,600, PAYOUT_FLOOR $52,100, QUAL 5x$250 qualifying days, CONSISTENCY
0.50 (no single day >=50% of profit since last payout), PAYOUT_EVERY_D=30 (attempt a payout sweep
every ~month once eligible), LADDER [1500,1500,2000,2500,2500,3000] then CLOSED_MAX (PA closes
after 6 payouts, ~$13k lifetime cap). Monthly rolling starts require >=12 months of forward runway
(same start-construction as `apex_funded_40.main()`).

CAVEAT (verbatim from `apex_funded_40`'s own caveats, `reports/apex_validation.json`
`funded_40_recert.caveats[0]`): "monthly rolling starts OVERLAP -> effective independent samples
~4-5, bust% has wide CI". Bust/safety-net/etc percentages below are OBSERVED IN THIS MODEL, not
guaranteed — treat every percentage in this file as a point estimate over a small number of
effectively-independent overlapping-start samples, not an i.i.d. probability.
"""
import os
import sys
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import apex_funded_40 as FM              # certified model — READ-ONLY import, never modified
import tools_sim_parity_check as SPC     # HONEST stream loader (load_rows, post-fix)

# ---- constants pulled from the certified module, never retyped ----
START, TRAIL, LOCK_EOD = FM.START, FM.TRAIL, FM.LOCK_EOD
PAYOUT_FLOOR, MIN_REQ, LADDER = FM.PAYOUT_FLOOR, FM.MIN_REQ, FM.LADDER
DLL, DAILY_STOP = FM.DLL, FM.DAILY_STOP
QUAL_DAY, QUAL_N, CONSISTENCY = FM.QUAL_DAY, FM.QUAL_N, FM.CONSISTENCY
PAYOUT_EVERY_D = FM.PAYOUT_EVERY_D

OVERLAP_CAVEAT = ("monthly rolling starts OVERLAP -> effective independent samples ~4-5, "
                   "bust% has wide CI")

# Sizing cells per task brief (mirrors the old research points; 480/A5 + 640/A5 are new additions).
CELLS = [
    (150, 2), (200, 2), (250, 4), (300, 4), (400, 4), (480, 4), (600, 6), (640, 4),
    (480, 5), (640, 5),
]

# Pre-fix (lookahead-contaminated) apex_funded_40 numbers at the equivalent (budget=160*a_size,
# cap=a_size) sizes, for transparency only (reports/apex_validation.json funded_40_recert) — these
# are INVALIDATED (04_invalidated_numbers.md #6) and are NOT expected to reproduce on the honest
# stream; printed for reference, not treated as a target.
PRE_FIX_REFERENCE = {
    3: dict(e_paid=11725, bust=0.0, med_months=17.8),
    4: dict(e_paid=12649, bust=0.0, med_months=16.1),
    5: dict(e_paid=12827, bust=0.0, med_months=15.9),
    6: dict(e_paid=12443, bust=2.0, med_months=14.9),
}


def daily_series(rows, budget, cap):
    """Generalization of apex_funded_40.daily_series to independent (budget $, cap contracts).

    Same rules verbatim: q = min(cap, int(budget // risk_usd)) per trade (skip if q<1); ARES
    $550 realized daily-stop cutoff (no more entries once the day's realized breaches it); Apex
    $1,000 DLL trough-clamp (day's marked-open-loss breaching -DLL clamps that day's realized to
    exactly -DLL, conservative same-bar sequencing). Reduces to apex_funded_40.daily_series exactly
    when budget == 160.0 * cap (verified in main()'s CANARY)."""
    ev = []
    for t in rows:
        risk1 = t["risk_usd"]
        q = min(cap, int(budget // risk1))
        if q < 1:
            continue
        ev.append((pd.Timestamp(t["ts"]), t["R"] * risk1 * q, min(0.0, t["mae_r"]) * risk1 * q))
    ev.sort(key=lambda x: x[0])
    days = {}
    for ts, pnl, mae in ev:
        d = ts.normalize()
        rec = days.setdefault(d, dict(real=0.0, trough=0.0, stopped=False))
        if rec["stopped"]:
            continue
        rec["trough"] = min(rec["trough"], rec["real"] + mae)
        rec["real"] += pnl
        if rec["real"] <= DAILY_STOP:
            rec["stopped"] = True
    out = []
    for d in sorted(days):
        r = days[d]
        real, trough = r["real"], r["trough"]
        if trough <= DLL:                              # Apex DLL cuts the day mid-flight
            real = max(real, DLL) if real < DLL else real
            real = DLL if real < DLL else real          # realized can't finish below the DLL cut
        out.append((d, real, trough))
    return out


def monthly_starts(days):
    """Identical rolling-monthly-start selection to apex_funded_40.main() (>=12mo runway)."""
    return [i for i, (d, _, _) in enumerate(days)
            if (days[-1][0] - d).days >= 365 and (i == 0 or days[i - 1][0].month != d.month)]


def run_pa_instrumented(days, start_i):
    """Same lifecycle rules as apex_funded_40.run_pa, reproduced verbatim, plus per-stage
    instrumentation (safety-net day, payout list, start year) needed for the funnel breakdown.
    Verified against apex_funded_40.run_pa outcome-for-outcome in main()'s CANARY."""
    bal, peak_eod, locked = START, START, False
    thr = START - TRAIL
    paid, ladder_i = 0.0, 0
    since = dict(profit=0.0, maxday=0.0, qual=0)
    t0 = days[start_i][0]
    last_sweep = t0
    safety_net_day = None
    payouts = []

    def result(outcome, d_last):
        return dict(outcome=outcome, day_offset=(d_last - t0).days,
                    months=(d_last - t0).days / 30.4, paid=paid, n_payouts=ladder_i,
                    safety_net_day=safety_net_day, payouts=list(payouts), start_year=t0.year)

    for i in range(start_i, len(days)):
        d, real, trough = days[i]
        if bal + min(0.0, trough) <= thr:
            return result("BUST", d)
        bal += real
        since["profit"] += real
        since["maxday"] = max(since["maxday"], real)
        if real >= QUAL_DAY:
            since["qual"] += 1
        peak_eod = max(peak_eod, bal)
        if safety_net_day is None and peak_eod >= LOCK_EOD:
            safety_net_day = (d - t0).days
        if not locked:
            thr = max(thr, peak_eod - TRAIL)
            if peak_eod >= LOCK_EOD:
                thr = START + 100.0
                locked = True
        if bal <= thr:
            return result("BUST", d)
        if (d - last_sweep).days >= PAYOUT_EVERY_D:
            last_sweep = d
            eligible = (bal >= MIN_REQ and since["qual"] >= QUAL_N
                        and (since["profit"] > 0 and since["maxday"] < CONSISTENCY * since["profit"]))
            if eligible:
                amt = min(LADDER[ladder_i], bal - PAYOUT_FLOOR)
                if amt > 0:
                    bal -= amt
                    paid += amt
                    ladder_i += 1
                    payouts.append(dict(index=ladder_i, day_offset=(d - t0).days, amount=amt))
                    since = dict(profit=0.0, maxday=0.0, qual=0)
                    if ladder_i >= len(LADDER):
                        return result("CLOSED_MAX", d)
    return result("DATA_END", days[-1][0])


def canary(rows):
    """Prove the generalized (budget, cap) daily_series + run_pa_instrumented reproduce
    apex_funded_40.daily_series/run_pa EXACTLY when parameterized equivalently
    (budget=160*a_size, cap=a_size), on the SAME stream, before trusting anything below."""
    print("CANARY -- generalized runner vs apex_funded_40.daily_series/run_pa "
          "(budget=160*a_size, cap=a_size), same honest stream:")
    all_ok = True
    for a_size in (3, 4, 5, 6):
        days_orig = FM.daily_series(rows, a_size)
        days_mine = daily_series(rows, 160.0 * a_size, a_size)
        if days_orig != days_mine:
            print(f"  [MISMATCH] A{a_size}: daily_series diverges\n"
                  f"    orig[:3]={days_orig[:3]}\n    mine[:3]={days_mine[:3]}")
            all_ok = False
            continue
        starts = monthly_starts(days_orig)
        res_orig = [FM.run_pa(days_orig, s) for s in starts]
        res_mine = [run_pa_instrumented(days_mine, s) for s in starts]
        n_mismatch = 0
        for o1, o2 in zip(res_orig, res_mine):
            same = (o1[0] == o2["outcome"] and abs(o1[1] - o2["months"]) < 1e-9
                    and abs(o1[2] - o2["paid"]) < 1e-9 and o1[3] == o2["n_payouts"])
            if not same:
                n_mismatch += 1
        status = "OK" if n_mismatch == 0 else f"MISMATCH ({n_mismatch}/{len(starts)} starts)"
        if n_mismatch:
            all_ok = False
        print(f"  A{a_size}: daily_series identical, run_pa {status} (n={len(starts)} starts)")

        e_paid_now = round(float(np.mean([r["paid"] for r in res_mine])))
        bust_now = round(100 * sum(1 for r in res_mine if r["outcome"] == "BUST") / len(res_mine), 1)
        medm_now = round(float(np.median([r["months"] for r in res_mine])), 1)
        ref = PRE_FIX_REFERENCE[a_size]
        print(f"    honest-stream now: E[paid]=${e_paid_now:,} bust={bust_now}% med_months={medm_now}   "
              f"| pre-fix reference (INVALIDATED, apex_validation.json): "
              f"E[paid]=${ref['e_paid']:,} bust={ref['bust']}% med_months={ref['med_months']}")
    if not all_ok:
        print("[CANARY MISMATCH] STOPPING -- generalized runner does not reproduce the certified "
              "apex_funded_40 mechanics. Do not trust the cells below.")
        return False
    print("[canary OK] generalized (budget, cap) runner reproduces apex_funded_40.daily_series/"
          "run_pa exactly, trade-for-trade, on the honest stream. The pre-fix vs honest-now deltas "
          "printed above are the EXPECTED look-ahead-fix divergence (04_invalidated_numbers.md #6), "
          "not a code bug -- both numbers shown for transparency, no winner-picking.\n")
    return True


def cell_report(rows, budget, cap):
    days = daily_series(rows, budget, cap)
    starts = monthly_starts(days)
    res = [run_pa_instrumented(days, s) for s in starts]
    n = len(res)

    bust = [r for r in res if r["outcome"] == "BUST"]
    closed = [r for r in res if r["outcome"] == "CLOSED_MAX"]
    data_end = [r for r in res if r["outcome"] == "DATA_END"]
    reached_sn = [r for r in res if r["safety_net_day"] is not None]

    paid_all = [r["paid"] for r in res]
    months_all = [r["months"] for r in res]
    n_payouts_all = [r["n_payouts"] for r in res]

    payout_dist = {k: round(100 * sum(1 for x in n_payouts_all if x == k) / n, 1)
                   for k in range(len(LADDER) + 1)}

    per_year = {}
    for r in res:
        y = r["start_year"]
        rec = per_year.setdefault(y, dict(n=0, bust=0, closed=0, data_end=0))
        rec["n"] += 1
        if r["outcome"] == "BUST":
            rec["bust"] += 1
        elif r["outcome"] == "CLOSED_MAX":
            rec["closed"] += 1
        else:
            rec["data_end"] += 1
    per_year_pct = {y: dict(n=v["n"], bust_pct=round(100 * v["bust"] / v["n"], 1),
                             closed_pct=round(100 * v["closed"] / v["n"], 1),
                             data_end_pct=round(100 * v["data_end"] / v["n"], 1))
                    for y, v in sorted(per_year.items())}

    worst_day = round(float(min(r_ for _, r_, _ in days)), 0) if days else None

    return dict(
        budget=budget, cap=cap, n_starts=n,
        e_paid=round(float(np.mean(paid_all))),
        med_paid=round(float(np.median(paid_all))),
        med_months=round(float(np.median(months_all)), 1),
        bust_pct=round(100 * len(bust) / n, 1),
        closed_max_pct=round(100 * len(closed) / n, 1),
        data_end_pct=round(100 * len(data_end) / n, 1),
        safety_net_pct=round(100 * len(reached_sn) / n, 1),
        med_days_to_safety_net=(round(float(np.median([r["safety_net_day"] for r in reached_sn])), 1)
                                 if reached_sn else None),
        worst_day=worst_day,
        payout_count_dist_pct=payout_dist,
        per_start_year=per_year_pct,
    )


def main():
    print("loading HONEST D1c stream via tools_sim_parity_check.load_rows() "
          "(post-fix, INC-20260706-1141)…", flush=True)
    rows = SPC.load_rows()
    print(f"  n={len(rows)} rows", flush=True)

    ok = canary(rows)
    if not ok:
        return

    cells = []
    hdr = (f"{'budget':>7}{'cap':>5}{'n':>6}{'E[paid]$':>10}{'medpaid$':>10}{'medMo':>7}"
           f"{'bust%':>7}{'closed%':>9}{'dataend%':>10}{'SN%':>6}{'medDaySN':>10}{'worstDay':>10}")
    print(hdr)
    print("-" * len(hdr))
    for budget, cap in CELLS:
        r = cell_report(rows, budget, cap)
        cells.append(r)
        print(f"{r['budget']:>7}{r['cap']:>5}{r['n_starts']:>6}{r['e_paid']:>10,}"
              f"{r['med_paid']:>10,}{r['med_months']:>7}{r['bust_pct']:>7}{r['closed_max_pct']:>9}"
              f"{r['data_end_pct']:>10}{r['safety_net_pct']:>6}"
              f"{(r['med_days_to_safety_net'] if r['med_days_to_safety_net'] is not None else 0):>10}"
              f"{r['worst_day']:>10}")
    print("-" * len(hdr))
    print(f"CAVEAT (verbatim, apex_funded_40 funded_40_recert.caveats[0]): {OVERLAP_CAVEAT}")

    os.makedirs("reports/emergency_recert_d1c_lookahead", exist_ok=True)
    out = dict(
        label="HONEST-RECERT DRAFT — pending auditor verdict + operator approval",
        incident="INC-20260706-1141",
        stream="honest D1c (post-fix), tools_sim_parity_check.load_rows(), n=%d" % len(rows),
        rules_source="apex_funded_40.py (imported, not modified)",
        overlap_caveat=OVERLAP_CAVEAT,
        cells=cells,
    )
    with open("reports/emergency_recert_d1c_lookahead/08_honest_funded_funnel.json", "w") as f:
        import json
        json.dump(out, f, indent=1)
    print("\n[saved] reports/emergency_recert_d1c_lookahead/08_honest_funded_funnel.json")
    return cells


if __name__ == "__main__":
    main()
